name: PHP Testing

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2', '8.3']
        dep-version: ['', '--prefer-lowest']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        
    - name: Set master as the default Git branch to prevent warnings
      run: git config --global init.defaultBranch master

    - name: Install dependencies
      run: composer install --no-interaction --no-progress --no-suggest --prefer-dist ${{ matrix.dep-version }}

    - name: Run test suite
      run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover
      env:
        XDEBUG_MODE: coverage
      
    - name: Upload Scrutinizer coverage
      uses: sudo-bot/action-scrutinizer@latest
      with:
        cli-args: "--format=php-clover coverage.clover"
