name: PHP Testing

on: [push]

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['8.0', '8.1', '8.2', '8.3']
        dep-version: ['', '--prefer-lowest']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Show Git and SVN versions
      run: | 
        which git
        git --version
        which svn
        svn --version

    - name: Set master as the default Git branch to prevent warnings
      run: git config --global init.defaultBranch master

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}-

    - name: Install dependencies
      run: composer update --no-interaction --no-progress --no-suggest --prefer-dist ${{ matrix.dep-version }}

    - name: Run test suite
      run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
      env:
        XDEBUG_MODE: coverage
